const { Configuration, OpenAIApi } = require('openai');

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
});

const openai = new OpenAIApi(configuration);

const generateResumeContent = async (githubData, portfolioData) => {
  try {
    const prompt = `Given the following GitHub and portfolio data, generate a professional resume in JSON format. 
    Focus on creating a compelling summary, relevant skills, work experience, projects, and achievements.
    
    GitHub Data:
    ${JSON.stringify(githubData, null, 2)}
    
    Portfolio Data:
    ${JSON.stringify(portfolioData, null, 2)}
    
    Return a JSON object with the following structure:
    {
      "summary": "A professional summary highlighting key skills and experience",
      "skills": ["list", "of", "relevant", "skills"],
      "experience": [
        {
          "title": "Job/Project Title",
          "company": "Company/Project Name",
          "duration": "Time Period",
          "description": "Key responsibilities and achievements"
        }
      ],
      "projects": [
        {
          "name": "Project Name",
          "description": "Project description",
          "technologies": ["list", "of", "technologies"],
          "url": "Project URL if available"
        }
      ],
      "achievements": [
        "Notable achievement 1",
        "Notable achievement 2"
      ]
    }`;

    const response = await openai.createChatCompletion({
      model: "gpt-4",
      messages: [
        {
          role: "system",
          content: "You are a professional resume writer. Create a well-structured, professional resume based on the provided GitHub and portfolio data. Focus on clarity, impact, and relevance to the tech industry."
        },
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 1500
    });

    // Extract the JSON content from the response
    const content = response.data.choices[0]?.message?.content;
    if (!content) {
      throw new Error('No content generated by AI');
    }

    // Parse the JSON response
    const startIndex = content.indexOf('{');
    const endIndex = content.lastIndexOf('}') + 1;
    const jsonContent = content.substring(startIndex, endIndex);
    
    return JSON.parse(jsonContent);
  } catch (error) {
    console.error('Error in generateResumeContent:', error);
    throw new Error('Failed to generate resume content');
  }
};

module.exports = { generateResumeContent };